server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://hjt-code:3306/hjt-data?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 970628hjt.

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  config: classpath:logback-spring.xml


